name: Test generators
on: [pull_request, push]

env:
  IMAGE_NAME: generators
  IMAGE_PATH: /tmp/generators.tar

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - uses: docker/setup-buildx-action@2a1a44ac4aa01993040736bd95bb470da1a38365
      - uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        with:
          context: .
          tags: ${{ env.IMAGE_NAME }}:test
          outputs: type=docker,dest=${{ env.IMAGE_PATH }}
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08
        with:
          name: ${{ env.IMAGE_NAME }}
          path: ${{ env.IMAGE_PATH }}

  test:
    runs-on: ubuntu-latest
    needs: [build-docker]
    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
    - uses: docker/setup-buildx-action@2a1a44ac4aa01993040736bd95bb470da1a38365
    - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
      with:
        name: ${{ env.IMAGE_NAME }}
        path: /tmp
    - name: Load docker image
      run: |
        docker load --input ${{ env.IMAGE_PATH }}
    - name: Run tests
      run: |
        sudo ./test_generators.sh -b
